apiVersion: v1
kind: Service
metadata:
  name: server
spec:
  ports:
    - port: 3333
      targetPort: 3333
  selector:
    app: server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: leesanghoon94/server-local:v0.0.3
          imagePullPolicy: Always
          ports:
            - containerPort: 3333
          # env:
          #   - name: MYSQL_HOST
          #     valueFrom:
          #       configMapKeyRef:
          #         name: db-env
          #         key: mysql_host
          #   - name: MYSQL_PASSWORD
          #     valueFrom:
          #       secretKeyRef:
          #         name: mysql-password
          #         key: MYSQL_ROOT_PASSWORD
          #   - name: MYSQL_DATABASE
          #     valueFrom:
          #       configMapKeyRef:
          #         name: db-env
          #         key: mysql_database
          #   - name: MYSQL_USER
          #     valueFrom:
          #       configMapKeyRef:
          #         name: db-env
          #         key: mysql_user
          
